name: Fetch RSS Feed

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests pyyaml

      - name: Run Feed Script
        run: python fetch_linkedin.py

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _data/rss.yml
          git commit -m "Update RSS feed" || echo "No changes"
          git push
