name: Scrape LinkedIn Posts

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm run scrape

      - name: Commit and push scraped data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _data/linkedin_feed.yml
          git commit -m "Update LinkedIn feed [auto]" || echo "No changes"
          git push
